### ISSUE TITLE
index.d.ts won't compile with Typescript 2.9

### ISSUE THREAD

**Issue by just-jeb** [bpmn-io/tiny-svg#4]
The compilation fails with the following error: 

> ERROR in node_modules/tiny-svg/dist/index.d.ts(22,4): error TS1023: An index signature parameter type must be 'string' or 'number'.

Indeed the following definition [won't compile in TS 2.9](https://www.typescriptlang.org/play/#src=export%20interface%20KeyValue%3CTKey%20%3D%20string%2C%20TValue%20%3D%20any%3E%20%7B%0D%0A%20%20%5Bkey%3A%20TKey%5D%3A%20TValue%3B%0D%0A%7D):
```ts
export interface KeyValue<TKey = string, TValue = any> {
  [key: TKey]: TValue;
}
```

**Comment by nikku** [comment]
What would the right typescript definition for an object `{}`?

**Comment by just-jeb** [comment]
`any` I guess. But it depends on what you wanted to pass here. Should it be just `string` to `any` map? Should it be a map from type A to type B (all the values are B)? Please elaborate.

**Comment by nikku** [comment]
You're able to pass an arbitrary object (`string => any` map).

**Comment by nikku** [comment]
Is TS@2.9 the latest version?

**Comment by nikku** [comment]
Please verify if the following works for you:

```typescript
export interface KeyValue {
  [key: string]: any;
}
```

**Comment by just-jeb** [comment]
> Is TS@2.9 the latest version?

2.9.2, yes

> export interface KeyValue {
>   [key: string]: any;
> }

This was my ad hoc fix so yes, it works.
